### PR TITLE
Fix for #1071: Calendar events need to respect clinic hours

### LINKED ISSUE #1071: Calendar events need to respect clinic hours
The system will and does give an alert that the provider is not available but allows the action anyway. 

If you create an appointment for 1 pm and then change the time to 11 but forget to change the PM to am you now have an appointment set for 11 pm

image

The appointment should not be allowed if it is before or after the clinic hours.

image

The AM/PM flag should be set to reflect the clinic open hours.

So the clinic does not end up with this 

image

### PR DESCRIPTION
**Pull request by apooravc**
Fixes #1071 

Added a check for user selected time (taking AM/PM into account) to be within clinic hours. The check would alert the user and prevent the appointment from being made otherwise.

One way to see the changes _locally_ would be as follows:
1) Clone my repo via `git clone https://github.com/apooravc/LibreEHR.git`
2) After cloning, only the master branch would be available locally. Enter `git checkout -b check-cal-event origin/check-cal-event` or `git branch check-cal-event origin/check-cal-event` to get the branch _check-cal-event_ locally.
3) The changes could then be seen on Calendar screen.

@teryhill Please have a look.

### CODE REVIEW

**Comment by aethelwulffe** [comment]
I will look, but we also have #1072 PR on this.  We need to do a collaboration of methods.  We also need to start assigning people to issues.  Assignments should be made to people who are validly active, and we need to start maintaining out lists of contributors by ensuring they can add labels and get assignments.
-We need to review our github ACL...

**Comment by apooravc** [comment]
I understand your concerns @aethelwulffe , how does a gallery of active contributors with their Github profile image and link on the README of this repo sounds? Sort of like [OpenEMR](https://github.com/openemr/openemr) has on their Github repo.

About this PR and issue, I was already assigned by @teryhill and I pushed a solution as soon as I could.

**Comment by aethelwulffe** [comment]
We have the gallery here too...Complete with the top contributor who committed/attested almost everything under his own name...author or not...from the fork source.  What I am talking about is being able to cleanly allow walk-in contributors to add labels, and easily enable assignment of issues to people (or self-assign).  Since word is that a move to gitlab is being forced, I suppose that is an issue for later.

**Comment by apooravc** [comment]
@teryhill Added a `GLOBAL` to turn this feature on/off. Please have a look.

File: modules/calendar/add_edit_event.php [hunk 1]
```diff
@@ -230,6 +230,28 @@ function DOBandEncounter()
         if ($_POST['form_ampm'] == '2' && $tmph < 12) $tmph += 12;
         $duration = abs($_POST['form_duration']); // fixes #395
     }
+    //check for selected appointment time
+    if ($GLOBALS['check_appt_time'] == '1') {
```
Comment (teryhill) [inline modules/calendar/add_edit_event.php]: I had to make this if ($GLOBALS['check_appt_time'] == 1) to get it to work on my system

**Comment by teryhill** [comment]
@apooravc I am having an issue with the global working. See my code comment.

File: modules/calendar/add_edit_event.php (hunk 1 above)
Comment (apooravc) [reply modules/calendar/add_edit_event.php]: @teryhill I thought this global was carrying the string 1 rather than numeric 1 when checked. Apparently, that's not the case.

**Comment by apooravc** [comment]
@teryhill Did the required changes. Please have a look.

**Comment by Trodrige** [comment]
@apooravc I'm testing this. Nothing happens when I click 'All', 'Current' or 'Future'. I can only cancel. See below
apoorv

My 'Check clinic hours' global is checked
apoorv1

**Comment by aethelwulffe** [comment]
OK, it is working in either case with the gobals.

**Comment by aethelwulffe** [comment]
I am good with leaving it as a default off (unset in the array).  I checked it before testing though, so I don't know what happens if you don't set the global array value before starting.  It has a conditional statement, and probably would not crash even if it didn't.
