### PR TITLE
Fixes bug of freezing when right most bar resized

### LINKED ISSUE #862: Everything freezes when try to resize the tab from the far right side of the far right tab
Refresh the site. Drag the right border of the tab. If there two tabs, drag the right border of the right tab. But do it, when you have this cursor.
resize_cursor

Then everything freezes and you still have resize cursor.

### PR DESCRIPTION
**Pull request by abhigyank**
Fixes #862 

Changed position of deactivating Frame Barrier to be called everytime at the end of activating Frame Barrier whenever mouse button is released after resizing.

### CODE REVIEW

**Comment by teryhill** [comment]
You need to do a gitnor on the sqlconf.php. That is for your local machine only and does not need to be sent in. Delete it out of your pull request.

File: interface/main/tabs/main.php [hunk 1]
```diff
@@ -192,15 +192,14 @@ function isEncounterLocked( encounterId ) {
...
-                            $("#frameBarrier").css("visibility", "hidden");
-                        });
                     }
+                    $(document).on("mouseup", function() {
+                        $('body').css('cursor', priorCursor);
+                        $('.draggable').removeClass('draggable').css('z-index', z_idx);
+                        
+                        // Deactivate Frame Barrier!
+                        $("#frameBarrier").css("visibility", "hidden");
+                    });
```
Comment (teryhill) [inline interface/main/tabs/main.php]: I don't see a change

Comment (abhigyank) [reply interface/main/tabs/main.php]: Have moved the deactivation barrier part out of the offset ```if``` condition, so that it runs even for the right side of right most tab.

Comment (teryhill) [reply interface/main/tabs/main.php]: Okay I see the move now. It tests well. Have you got any Ideas on how to improve the tabs?

Comment (abhigyank) [reply interface/main/tabs/main.php]: The changes are okay for the PR to be merged right?
What improvements are to be made on the tabs? Is it to be done in this PR?

**Comment by teryhill** [comment]
The changes are ok. The improvement to the tabs are just what you find that are needed. Remove the config file from the PR and I will get this merged.

**Comment by abhigyank** [comment]
I have removed the config file. 
I would like to know what improvements are required to tabs. We can discuss that and maybe I can create a new PR for that?

**Comment by teryhill** [comment]
@abhigyank Open 3 tabs. then unlock two of them and close the third
Like this 

image

Then close the open tab

image

It would be good if the unlocked tabs opened when there was nothing on the screen

**Comment by abhigyank** [comment]
@teryhill I get the issue. I'll create a new issue for this and work separately on it.

**Comment by aethelwulffe** [comment]
Behavior:
On log-in, rightmost tab has resize tooltip.
Add third tab, and the rightmost no-longer has tooltip.
Open fourth tab, and only the left two are resizable.
Close the two left tabs, and none of the remaining are resizable.

Open or close any tabs you like (even all of them).  You never get your resize back.

Trying this install again...but I am approving just on the basis that there is no actual tab freeze.

Errors noted during testing (resulting in the browser responding slower and slower):  May be due to my particular test instance (needs clean update).
```
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  main_info.php:46
jQuery.Deferred exception: t.options is undefined s</r.prototype.instantiateView@http://localhost/MIPS/modules/calendar/full_calendar_scheduler/scheduler.min.js:6:16579
renderView@http://localhost/MIPS/modules/calendar/full_calendar/fullcalendar.min.js:9:25223
initialRender@http://localhost/MIPS/modules/calendar/full_calendar/fullcalendar.min.js:9:24453
render@http://localhost/MIPS/modules/calendar/full_calendar/fullcalendar.min.js:9:23740
t.fn.fullCalendar/<@http://localhost/MIPS/modules/calendar/full_calendar/fullcalendar.min.js:6:21311
each@http://localhost/MIPS/modules/calendar/full_calendar/lib/jquery.min.js:2:2713
each@http://localhost/MIPS/modules/calendar/full_calendar/lib/jquery.min.js:2:1001
t.fn.fullCalendar@http://localhost/MIPS/modules/calendar/full_calendar/fullcalendar.min.js:6:21091
@http://localhost/MIPS/modules/calendar/index.php?&framewidth=712:48:7
j@http://localhost/MIPS/modules/calendar/full_calendar/lib/jquery.min.js:2:29997
g/</k<@http://localhost/MIPS/modules/calendar/full_calendar/lib/jquery.min.js:2:30313
 undefined  jquery.min.js:2:31569
TypeError: t.options is undefined[Learn More]
```

**Comment by teryhill** [comment]
I noticed that error in waterfox a few days back @aethelwulffe  so I know it is not related to this PR.

**Comment by abhigyank** [comment]
@aethelwulffe I am able to reproduce the behavior you're reporting. For that too, I think a separate issue with a bug label needs to be created and worked on.

**Comment by aethelwulffe** [comment]
Yeah, we can do up an issue and go with that...though I bet there is an existing issue related to resize of tabs.  It is an old problem.
