### PR TITLE
Fix for #242: Notify when globals saved

### LINKED ISSUE #242: Some Frames need be configuration to Close on Select
Frames like the Patient Finder and Globals should close themselves after you take the end-action (like selection of the patient or "Save".

This probably could be configurable but maybe not necessary.

### PR DESCRIPTION
**Pull request by apooravc**
Fixes #242 
When the user clicks on save, and the edit_globals iframe is refreshed, there is no notification given to users. This PR adds a notification shown below which fades out after `3 seconds`:
image1

Works on the value of `$_GET['unique']` which is `null` on first opening edit_globals or refreshing it by clicking on refresh icon. It becomes equal to `yes` after clicking on save button.

@aethelwulffe @teryhill Please have a look.

### CODE REVIEW

**Comment by teryhill** [comment]
Looks good and tests well.

File: interface/super/edit_globals.php [hunk 1]
```diff
@@ -374,6 +374,16 @@ function checkBackgroundServices(){
 
 <body class="body_top">
 
+<!--Settings Saved Notification for Globals-->
+<div id="set_alert" style="width: 130px; background-color: #2ECC40; color: #fff; font-weight: bold; font-size: 17px; text-align: center; margin-bottom: 5px; display: none;">Settings Saved</div>
+<?php if ($_GET['unique'] == "yes") { ?>
+<script type="text/javascript">
+  $(document).ready(function() {
+    $("div#set_alert").css("display", "block").fadeOut(3000);
```
Comment (aethelwulffe) [inline interface/super/edit_globals.php]: Very long fade.  No real harm.
